version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: exam-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ExamPlatformDB

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exam-api
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=ExamPlatformDB

volumes:
  mongodb_data:
