<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Repositories\**" />
    <Compile Remove="**\* copy.cs" />
    <Compile Remove="AdminServices.cs" />
    <Compile Remove="AuthService.cs" />
    <Compile Remove="GoogleTokenValidator.cs" />
    <Compile Remove="IAuthService.cs" />
    <Compile Remove="IEmailSender.cs" />
    <Compile Remove="IGoogleTokenValidator.cs" />
    <Compile Remove="SmtpEmailSender.cs" />
    <Compile Remove="Student.cs" />
    <Compile Remove="Models\AuthDtos.cs" />
    <Compile Remove="Models\User\UserCreateDTO.cs" />
    <Compile Remove="Models\User\UserResponseDTO.cs" />
    <Compile Remove="Models\User\UserUpdateDTO.cs" />
    <Content Remove="Repositories\**" />
    <EmbeddedResource Remove="Repositories\**" />
    <None Remove="Repositories\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

</Project>
